# Generated by Django 3.1 on 2021-04-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='رشته تحصیلی')),
            ],
            options={
                'verbose_name': 'رشته دانشگاهی',
                'verbose_name_plural': 'رشته های دانشگاهی',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='عنوان')),
                ('code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='کد کارت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ و ز مان بروز رسانی')),
            ],
            options={
                'verbose_name': 'کارت حفاظتی',
                'verbose_name_plural': 'کارت های حفاظتی',
            },
        ),
        migrations.CreateModel(
            name='Chevron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='عنوان')),
                ('code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='کد درجه')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و ز مان بروز رسانی')),
            ],
            options={
                'verbose_name': 'درجه نظامی',
                'verbose_name_plural': 'درجات نظامی',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='عنوان دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی رویداد',
                'verbose_name_plural': 'دسته بندی های رویداد ها',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='عنوان')),
                ('code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='کد تخصص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و ز مان بروز رسانی')),
            ],
            options={
                'verbose_name': 'تخصص و رسته',
                'verbose_name_plural': 'تخصص ها و رسته ها',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نام')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و ز مان بروز رسانی')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.CreateModel(
            name='StatusEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='عنوان')),
                ('code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='کد وضعیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و ز مان بروز رسانی')),
            ],
            options={
                'verbose_name': 'وضعیت تجهیزات',
                'verbose_name_plural': 'وضعیت های تجهیزات',
            },
        ),
        migrations.CreateModel(
            name='ToolsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='عنوان دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی تجهیزات',
                'verbose_name_plural': 'دسته بندی های تجهیزات',
            },
        ),
        migrations.CreateModel(
            name='ZonetHreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و ز مان بروز رسانی')),
            ],
            options={
                'verbose_name': 'تهدید منطقه ای',
                'verbose_name_plural': 'تهدیدات منطقه ای',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و ز مان بروز رسانی')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicInformations.state', verbose_name='استان مربوطه')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر ها',
            },
        ),
    ]
