# Generated by Django 3.1 on 2021-04-06 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Garrisons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardTablet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='لوحه نگهبانی کادر و وظیفه گروه دژبان', max_length=550, verbose_name='عنوان لوحه')),
                ('apply_date', models.DateField(unique=True, verbose_name='تاریخ لوحه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروز رسانی')),
                ('garrison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Garrisons.garrison', verbose_name='پایگاه')),
            ],
            options={
                'verbose_name': 'لوحه نگهبانی',
                'verbose_name_plural': 'لوحه های نگهبانی',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان پست نگهبانی')),
                ('weapon', models.CharField(choices=[('فاقد اسلحه', 'فاقد اسلحه'), ('MP4 - 20 تیر', 'MP4 - 20 تیر'), ('ژ 3 - 20 تیر', 'ژ 3 - 20 تیر'), ('کلت برونینگ - 12 تیر', 'کلت برونینگ - 12 تیر'), ('کلاشینکف - 20 تیر', 'کلاشینکف - 20 تیر'), ('باتوم', 'باتوم'), ('شوکر', 'شوکر'), ('باتوم و شوکر', 'باتوم و شوکر'), ('دیگر', 'دیگر')], default='A', max_length=50, verbose_name='سلاح')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروز رسانی')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Garrisons.location', verbose_name='مکان')),
            ],
            options={
                'verbose_name': 'پست نگهبانی',
                'verbose_name_plural': 'پست های نگهبانی',
            },
        ),
        migrations.CreateModel(
            name='SoldierMilitaryPolice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروز رسانی')),
                ('soldier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Garrisons.soldier', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'وظیفه پلیس هوایی',
                'verbose_name_plural': 'وظیفه های پلیس هوایی',
            },
        ),
        migrations.CreateModel(
            name='SoldierGuard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(choices=[(datetime.time(0, 0), '00:00'), (datetime.time(0, 30), '00:30'), (datetime.time(1, 0), '01:00'), (datetime.time(1, 30), '01:30'), (datetime.time(2, 0), '02:00'), (datetime.time(2, 30), '02:30'), (datetime.time(3, 0), '03:00'), (datetime.time(3, 30), '03:30'), (datetime.time(4, 0), '04:00'), (datetime.time(4, 30), '04:30'), (datetime.time(5, 0), '05:00'), (datetime.time(5, 30), '05:30'), (datetime.time(6, 0), '06:00'), (datetime.time(6, 30), '06:30'), (datetime.time(7, 0), '07:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30'), (datetime.time(21, 0), '21:00'), (datetime.time(21, 30), '21:30'), (datetime.time(22, 0), '22:00'), (datetime.time(22, 30), '22:30'), (datetime.time(23, 0), '23:00'), (datetime.time(23, 30), '23:30')], verbose_name='ساعت شروع پست')),
                ('shift_end', models.TimeField(choices=[(datetime.time(0, 0), '00:00'), (datetime.time(0, 30), '00:30'), (datetime.time(1, 0), '01:00'), (datetime.time(1, 30), '01:30'), (datetime.time(2, 0), '02:00'), (datetime.time(2, 30), '02:30'), (datetime.time(3, 0), '03:00'), (datetime.time(3, 30), '03:30'), (datetime.time(4, 0), '04:00'), (datetime.time(4, 30), '04:30'), (datetime.time(5, 0), '05:00'), (datetime.time(5, 30), '05:30'), (datetime.time(6, 0), '06:00'), (datetime.time(6, 30), '06:30'), (datetime.time(7, 0), '07:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30'), (datetime.time(21, 0), '21:00'), (datetime.time(21, 30), '21:30'), (datetime.time(22, 0), '22:00'), (datetime.time(22, 30), '22:30'), (datetime.time(23, 0), '23:00'), (datetime.time(23, 30), '23:30')], verbose_name='ساعت پایان پست')),
                ('shift_ends_next_day', models.BooleanField(default=False, verbose_name='روز بعد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و زمان بروز رسانی')),
                ('guard_tablet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soldiers_on_guard', to='Guards.guardtablet', verbose_name='لوحه نگهبانی')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soldiers_on_this_postion', to='Guards.position', verbose_name='پست')),
                ('soldier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guards.soldiermilitarypolice', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'وظیفه پلیس هوایی',
                'verbose_name_plural': 'وظیفه های پلیس هوایی',
            },
        ),
        migrations.CreateModel(
            name='PersonalMilitaryPolice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و زمان بروز رسانی')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Garrisons.personal', verbose_name='پایور')),
            ],
            options={
                'verbose_name': 'پایور پلیس هوایی',
                'verbose_name_plural': 'پایوران پلیس هوایی',
            },
        ),
        migrations.CreateModel(
            name='PersonalGuard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(choices=[(datetime.time(0, 0), '00:00'), (datetime.time(0, 30), '00:30'), (datetime.time(1, 0), '01:00'), (datetime.time(1, 30), '01:30'), (datetime.time(2, 0), '02:00'), (datetime.time(2, 30), '02:30'), (datetime.time(3, 0), '03:00'), (datetime.time(3, 30), '03:30'), (datetime.time(4, 0), '04:00'), (datetime.time(4, 30), '04:30'), (datetime.time(5, 0), '05:00'), (datetime.time(5, 30), '05:30'), (datetime.time(6, 0), '06:00'), (datetime.time(6, 30), '06:30'), (datetime.time(7, 0), '07:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30'), (datetime.time(21, 0), '21:00'), (datetime.time(21, 30), '21:30'), (datetime.time(22, 0), '22:00'), (datetime.time(22, 30), '22:30'), (datetime.time(23, 0), '23:00'), (datetime.time(23, 30), '23:30')], verbose_name='ساعت شروع پست')),
                ('shift_end', models.TimeField(choices=[(datetime.time(0, 0), '00:00'), (datetime.time(0, 30), '00:30'), (datetime.time(1, 0), '01:00'), (datetime.time(1, 30), '01:30'), (datetime.time(2, 0), '02:00'), (datetime.time(2, 30), '02:30'), (datetime.time(3, 0), '03:00'), (datetime.time(3, 30), '03:30'), (datetime.time(4, 0), '04:00'), (datetime.time(4, 30), '04:30'), (datetime.time(5, 0), '05:00'), (datetime.time(5, 30), '05:30'), (datetime.time(6, 0), '06:00'), (datetime.time(6, 30), '06:30'), (datetime.time(7, 0), '07:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30'), (datetime.time(21, 0), '21:00'), (datetime.time(21, 30), '21:30'), (datetime.time(22, 0), '22:00'), (datetime.time(22, 30), '22:30'), (datetime.time(23, 0), '23:00'), (datetime.time(23, 30), '23:30')], verbose_name='ساعت پایان پست')),
                ('shift_ends_next_day', models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, verbose_name='روز بعد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و زمان بروز رسانی')),
                ('guard_tablet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personals_on_guard', to='Guards.guardtablet', verbose_name='لوحه نگهبانی')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guards.personalmilitarypolice', verbose_name='پایور')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guards.position', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'پایور پلیس هوایی',
                'verbose_name_plural': 'پایوران پلیس هوایی',
            },
        ),
    ]
