# Generated by Django 3.1 on 2021-04-06 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BasicInformations', '0001_initial'),
        ('Garrisons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان اعتبار')),
                ('number', models.CharField(max_length=60, null=True, unique=True, verbose_name='شماره امریه')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مبلغ به ریال')),
                ('receive_date', models.DateField(verbose_name='تاریخ دریافت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ و ز مان بروز رسانی')),
                ('garrison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garrisons.garrison', verbose_name='یگان دریافت کننده')),
            ],
            options={
                'verbose_name': 'اعتبار',
                'verbose_name_plural': 'اعتبارات',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نام')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و ز مان بروز رسانی')),
                ('garrison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Garrisons.garrison', verbose_name='پایگاه مربوطه')),
                ('zonet_hreats', models.ManyToManyField(blank=True, to='BasicInformations.ZonetHreat', verbose_name='تهدیدات منطقه ای')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار ها',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('description_equipment', models.TextField(blank=True, null=True, verbose_name='شرح کالا')),
                ('brand', models.CharField(blank=True, max_length=60, null=True, verbose_name='برند')),
                ('model', models.CharField(blank=True, max_length=60, null=True, verbose_name='مدل')),
                ('serial_number', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='شماره سریال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='UploadFiles\\Images\\Equipments', verbose_name='تصویر')),
                ('files', models.FileField(blank=True, null=True, upload_to='UploadFiles\\EquipmentFiles', verbose_name='فایل')),
                ('sis_number', models.CharField(max_length=60, unique=True, verbose_name='شماره SIS')),
                ('lp_number', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='شماره LP')),
                ('buy_date', models.DateField(null=True, verbose_name='تاریخ خرید')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='قیمت خرید به ریال')),
                ('imperialistic', models.CharField(blank=True, max_length=60, null=True, verbose_name='بهره بردار')),
                ('imperialistic_date', models.DateField(verbose_name='تاریخ بهره برداری')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9.+]', 'فقط عدد و نقطه مجاز است.')], verbose_name='آدرس IP')),
                ('port_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='شماره پورت')),
                ('deploy_location', models.CharField(blank=True, max_length=60, null=True, verbose_name='محل استقرار')),
                ('level_info', models.BooleanField(verbose_name='شامل اطلاعات طبقه بندی شده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و ز مان بروز رسانی')),
                ('buy_expert', models.ForeignKey(blank=True, limit_choices_to={'is_buy_expert': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_bought_equipments', to='Garrisons.personal', verbose_name='کارشناس خرید')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_equipments', to='Garrisons.personal', verbose_name='عامل خرید')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicInformations.toolscategory', verbose_name='دسته بندی')),
                ('charges', models.ManyToManyField(blank=True, help_text='مشخص کنید از کدام اعتبار(های) دریافتی، خریداری شده است.', null=True, to='Stores.Charge', verbose_name='اعتبارات')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stores.depot', verbose_name='انبار')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Garrisons.location', verbose_name='مکان تحویل گیرنده')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Garrisons.owner', verbose_name='ذی حساب')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'تجهیزات',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نام')),
                ('address', models.TextField(verbose_name='آدرس دقیق')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9+]', 'فقط عدد وارد کنید.')], verbose_name='شماره تلفن')),
                ('manager_full_name', models.CharField(blank=True, max_length=11, null=True, verbose_name='نام و نشان مدیر')),
                ('manager_mobile_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9+]', 'فقط عدد وارد کنید.')], verbose_name='تلفن همراه مدیر')),
                ('information_security_license', models.CharField(blank=True, help_text='شماره امریه یا نامه حفاظت اطلاعات، که مبنی بر تایید فروشگاه می باشد.', max_length=30, null=True, verbose_name='مجوز حفاظت اطلاعات')),
                ('samta_license', models.CharField(blank=True, max_length=30, null=True, verbose_name='مجوز سمتا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و ز مان بروز رسانی')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicInformations.city', verbose_name='شهر مربوطه')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه ها',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date_time', models.DateTimeField(verbose_name='تاریخ و زمان رویداد')),
                ('precept_number', models.CharField(max_length=60, unique=True, verbose_name='شماره امریه')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درج')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ و ز مان بروز رسانی')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='Stores.equipment', verbose_name='کالا')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garrisons.location', verbose_name='مکان مقصد')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicInformations.statusequipment', verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تاریخچه',
                'verbose_name_plural': 'تاریخچه ها',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='Stores.shop', verbose_name='تهیه شده از فروشگاه'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicInformations.statusequipment', verbose_name='وضعیت فعلی'),
        ),
    ]
